# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 84f20f153154d544a185e0ab951e9c38fd168484af0ee8a744de5d7d158593132d8a1ba8bd309df3888faec995d23bb9d525257bd7de13e66beaddbf3bbedc55

test:
  secret_key_base: 09d9695d2e3108e020af9220ae0d383b70e7ec38d08201d1d513b22be674ff751b14c69e9d829b86ff5e0fdc0a0af9e595493503c9f0fd1d2adb3e21ac4a32b9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
