checkbd:
  image: mysql
  ports:
    - "8091:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=dev

checkapi:
  build: .
  environment:
    RAILS_ENV: development
  ports:
    - '8090:3000'
  links:
    - "checkbd"